using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Cairn.SourceGenerators;

/// <summary>Generates a strongly-typed <c>Cairn.Routes</c> catalog from named minimal-API endpoints.</summary>
[Generator(LanguageNames.CSharp)]
public sealed class RoutesGenerator : IIncrementalGenerator
{
    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var routes = context.SyntaxProvider.CreateSyntaxProvider(
                predicate: static (node, _) => IsWithNameInvocation(node),
                transform: static (syntaxContext, _) => Extract((InvocationExpressionSyntax)syntaxContext.Node))
            .Where(static route => route is not null)
            .Select(static (route, _) => route!.Value)
            .Collect();

        context.RegisterSourceOutput(routes, static (production, collected) => Generate(production, collected));
    }

    private static bool IsWithNameInvocation(SyntaxNode node)
        => node is InvocationExpressionSyntax { Expression: MemberAccessExpressionSyntax { Name.Identifier.ValueText: "WithName" } };

    private static RouteInfo? Extract(InvocationExpressionSyntax withName)
    {
        if (FirstStringLiteral(withName) is not { } name)
        {
            return null;
        }

        var receiver = ((MemberAccessExpressionSyntax)withName.Expression).Expression;
        return FindRouteTemplate(receiver) is { } template ? new RouteInfo(name, ParseParameters(template)) : null;
    }

    private static string? FindRouteTemplate(ExpressionSyntax expression)
    {
        while (expression is InvocationExpressionSyntax invocation && invocation.Expression is MemberAccessExpressionSyntax member)
        {
            if (member.Name.Identifier.ValueText is "MapGet" or "MapPost" or "MapPut" or "MapDelete" or "MapPatch" or "MapMethods")
            {
                return FirstStringLiteral(invocation);
            }

            expression = member.Expression;
        }

        return null;
    }

    private static string? FirstStringLiteral(InvocationExpressionSyntax invocation)
    {
        var argument = invocation.ArgumentList.Arguments.FirstOrDefault();
        return argument?.Expression is LiteralExpressionSyntax literal && literal.IsKind(SyntaxKind.StringLiteralExpression)
            ? literal.Token.ValueText
            : null;
    }

    // Encodes the route's parameters as "name:type|name2:type2".
    private static string ParseParameters(string template)
    {
        var parameters = new List<string>();
        var index = 0;

        while (index < template.Length)
        {
            if (template[index] != '{')
            {
                index++;
                continue;
            }

            var end = template.IndexOf('}', index);
            if (end < 0)
            {
                break;
            }

            var content = template.Substring(index + 1, end - index - 1).TrimStart('*');
            var colon = content.IndexOf(':');
            string name;
            var type = "string";

            if (colon >= 0)
            {
                name = content.Substring(0, colon);
                type = MapConstraint(content.Substring(colon + 1).Split(':')[0].Split('(')[0]);
            }
            else
            {
                name = content;
            }

            name = name.TrimEnd('?');
            if (IsIdentifier(name))
            {
                parameters.Add(name + " " + type);
            }

            index = end + 1;
        }

        return string.Join("|", parameters);
    }

    private static string MapConstraint(string constraint) => constraint switch
    {
        "int" => "int",
        "long" => "long",
        "bool" => "bool",
        "double" => "double",
        "float" => "float",
        "decimal" => "decimal",
        "guid" => "global::System.Guid",
        "datetime" => "global::System.DateTime",
        _ => "string",
    };

    private static void Generate(SourceProductionContext context, ImmutableArray<RouteInfo> routes)
    {
        if (routes.IsDefaultOrEmpty)
        {
            return;
        }

        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine("namespace Cairn");
        builder.AppendLine("{");
        builder.AppendLine("    /// <summary>Strongly-typed route references generated from named endpoints.</summary>");
        builder.AppendLine("    public static partial class Routes");
        builder.AppendLine("    {");

        var emitted = new HashSet<string>();
        foreach (var route in routes)
        {
            var method = Sanitize(route.Name);
            if (method.Length == 0 || !emitted.Add(method))
            {
                continue;
            }

            var parameters = Decode(route.Parameters);
            var signature = string.Join(", ", parameters.Select(static p => p.Type + " " + Escape(p.Name)));
            var values = parameters.Count == 0
                ? "null"
                : "new { " + string.Join(", ", parameters.Select(static p => Escape(p.Name))) + " }";

            builder.AppendLine($"        /// <summary>Route to the '{route.Name}' endpoint.</summary>");
            builder.AppendLine($"        public static global::Cairn.LinkTarget {method}({signature})");
            builder.AppendLine($"            => global::Cairn.LinkTarget.Route(\"{route.Name}\", {values});");
            builder.AppendLine();
        }

        builder.AppendLine("    }");
        builder.AppendLine("}");

        context.AddSource("Cairn.Routes.g.cs", builder.ToString());
    }

    private static List<(string Name, string Type)> Decode(string encoded)
        => encoded.Length == 0
            ? new List<(string, string)>()
            : encoded.Split('|').Select(static part => part.Split(' ')).Select(static pieces => (pieces[0], pieces[1])).ToList();

    private static string Sanitize(string routeName)
    {
        var builder = new StringBuilder();
        var capitalizeNext = true;

        foreach (var c in routeName)
        {
            if (char.IsLetterOrDigit(c))
            {
                builder.Append(capitalizeNext ? char.ToUpperInvariant(c) : c);
                capitalizeNext = false;
            }
            else
            {
                capitalizeNext = true;
            }
        }

        var result = builder.ToString();
        return result.Length > 0 && char.IsDigit(result[0]) ? "_" + result : result;
    }

    private static string Escape(string name)
        => SyntaxFacts.GetKeywordKind(name) != SyntaxKind.None || SyntaxFacts.GetContextualKeywordKind(name) != SyntaxKind.None
            ? "@" + name
            : name;

    private static bool IsIdentifier(string name)
        => name.Length > 0 && (char.IsLetter(name[0]) || name[0] == '_') && name.All(static c => char.IsLetterOrDigit(c) || c == '_');

    private readonly record struct RouteInfo(string Name, string Parameters);
}
